CREATE TABLE "majors" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "major_name" VARCHAR UNIQUE
);

CREATE TABLE "students" (
  "student_id" VARCHAR PRIMARY KEY,
  "student_name" VARCHAR,
  "email" VARCHAR UNIQUE,
  "major_id" INT NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course_no" INT,
  "course_name" VARCHAR UNIQUE
);

CREATE TABLE "sections" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course_id" INT NOT NULL,
  "section_number" VARCHAR,
  "semester" INT
);

CREATE TABLE "projects" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "old_project_no" VARCHAR,
  "project_no" VARCHAR,
  "title_th" VARCHAR,
  "title_en" VARCHAR,
  "abstract" TEXT,
  "relation_description" TEXT,
  "advisor_id" INT NOT NULL,
  "course_id" INT NOT NULL,
  "section_id" INT NOT NULL,
  "semester" INT,
  "project_status" VARCHAR,
  "academic_year" INT NOT NULL,
  "major_id" INT NOT NULL,
  "created_at" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "project_students" (
  "project_id" INT NOT NULL,
  "student_id" VARCHAR NOT NULL
);


CREATE TABLE "project_employees" (
  "project_id" INT NOT NULL,
  "employee_id" INT NOT NULL,
  "role_id" INT NOT NULL
);

CREATE TABLE "comments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "project_id" INT NOT NULL,
  "comment_text" TEXT,
  "created_at" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "employees" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "employee_name" VARCHAR,
  "email" VARCHAR UNIQUE,
  "role_id" INT NOT NULL,
  "created_at" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role_name" VARCHAR UNIQUE
);

CREATE TABLE "resource_types" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "resource_type" VARCHAR UNIQUE
);

CREATE TABLE "resources" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" VARCHAR,
  "project_id" INT NOT NULL,
  "resource_type_id" INT NOT NULL,
  "url" VARCHAR,
  "created_at" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "important_dates" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "major_id" INT NOT NULL,
  "event_date" DATE,
  "title" VARCHAR,
  "description" TEXT
);

-- Add foreign keys
ALTER TABLE "students" ADD FOREIGN KEY ("major_id") REFERENCES "majors" ("id");
ALTER TABLE "sections" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");
ALTER TABLE "projects" ADD FOREIGN KEY ("advisor_id") REFERENCES "employees" ("id");
ALTER TABLE "projects" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");
ALTER TABLE "projects" ADD FOREIGN KEY ("section_id") REFERENCES "sections" ("id");
ALTER TABLE "projects" ADD FOREIGN KEY ("major_id") REFERENCES "majors" ("id");
ALTER TABLE "project_students" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");
ALTER TABLE "project_students" ADD FOREIGN KEY ("student_id") REFERENCES "students" ("student_id");
ALTER TABLE "project_employees" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");
ALTER TABLE "project_employees" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("id");
ALTER TABLE "project_employees" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");
ALTER TABLE "comments" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");
ALTER TABLE "employees" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");
ALTER TABLE "resources" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");
ALTER TABLE "resources" ADD FOREIGN KEY ("resource_type_id") REFERENCES "resource_types" ("id");
ALTER TABLE "important_dates" ADD FOREIGN KEY ("major_id") REFERENCES "majors" ("id");