CREATE TABLE IF NOT EXISTS "roles" (
    "id" SERIAL PRIMARY KEY,
    "role_name" VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE "students" (
  "id" VARCHAR PRIMARY KEY,
  "student_name" VARCHAR,
  "email" VARCHAR UNIQUE,
  "major_id" INT NOT NULL
);

CREATE TABLE IF NOT EXISTS "students" (
    "id" VARCHAR(255) PRIMARY KEY,
    "prefix" VARCHAR(255) NOT NULL,
    "first_name" VARCHAR(255) NOT NULL,
    "last_name" VARCHAR(255) NOT NULL,
    "email" VARCHAR(255) UNIQUE NOT NULL,
    "major_id" INTEGER,
    FOREIGN KEY ("major_id") REFERENCES "majors"("id") ON DELETE SET NULL
);
CREATE TABLE IF NOT EXISTS "courses" (
    "id" SERIAL PRIMARY KEY,
    "course_no" VARCHAR(255) UNIQUE NOT NULL,
    "course_name" VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS "sections" (
    "id" SERIAL PRIMARY KEY,
    "course_id" INTEGER NOT NULL,
    "section_number" VARCHAR(255) NOT NULL,
    "semester" INTEGER NOT NULL,
    FOREIGN KEY ("course_id") REFERENCES "courses"("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "employees" (
    "id" SERIAL PRIMARY KEY,
    "prefix" VARCHAR(255) NOT NULL,
    "first_name" VARCHAR(255) NOT NULL,
    "last_name" VARCHAR(255) NOT NULL,
    "email" VARCHAR(255) UNIQUE NOT NULL,
    "role_id" INTEGER NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE SET NULL
);

CREATE TABLE "resource_types" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "resource_type" VARCHAR UNIQUE
);

CREATE TABLE "resources" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" VARCHAR,
  "project_id" INT NOT NULL,
  "resource_type_id" INT NOT NULL,
  "url" VARCHAR,
  "created_at" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "important_dates" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "major_id" INT NOT NULL,
  "event_date" DATE,
  "title" VARCHAR,
  "description" TEXT
);

-- Add foreign keys
ALTER TABLE "students" ADD FOREIGN KEY ("major_id") REFERENCES "majors" ("id");
ALTER TABLE "sections" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");
ALTER TABLE "projects" ADD FOREIGN KEY ("advisor_id") REFERENCES "employees" ("id");
ALTER TABLE "projects" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");
ALTER TABLE "projects" ADD FOREIGN KEY ("section_id") REFERENCES "sections" ("id");
ALTER TABLE "projects" ADD FOREIGN KEY ("major_id") REFERENCES "majors" ("id");
ALTER TABLE "project_students" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");
ALTER TABLE "project_students" ADD FOREIGN KEY ("student_id") REFERENCES "students" ("id");
ALTER TABLE "project_employees" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");
ALTER TABLE "project_employees" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("id");
ALTER TABLE "project_employees" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");
ALTER TABLE "comments" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");
ALTER TABLE "employees" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");
ALTER TABLE "resources" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");
ALTER TABLE "resources" ADD FOREIGN KEY ("resource_type_id") REFERENCES "resource_types" ("id");
ALTER TABLE "important_dates" ADD FOREIGN KEY ("major_id") REFERENCES "majors" ("id");