CREATE TABLE "majors" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "major_name" varchar UNIQUE
);

CREATE TABLE "project_number_counters" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "number" int,
  "academic_year" int NOT NULL,
  "semester" int,
  "course_id" int NOT NULL
);

CREATE TABLE "configs" (
  "config_name" varchar UNIQUE NOT NULL,
  "value" varchar NOT NULL
);

CREATE TABLE "students" (
  "id"  varchar PRIMARY KEY,
  "prefix" varchar,
  "first_name" varchar,
  "last_name" varchar,
  "email" varchar UNIQUE,
  "major_id" int NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course_no" varchar UNIQUE,
  "course_name" varchar UNIQUE,
  "semester" int NOT NULL,
  "major_id" int NOT NULL
);

CREATE TABLE "projects" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "old_project_no" varchar,
  "project_no" varchar UNIQUE,
  "title_th" varchar,
  "title_en" varchar,
  "abstract" text,
  "relation_description" text,
  "academic_year" int NOT NULL,
  "semester" int,
  "section_id" varchar,
  "is_approved" bool DEFAULT false,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "course_id" int NOT NULL,
  "major_id" int NOT NULL
);

CREATE TABLE "project_students" (
  "project_id" int NOT NULL,
  "student_id" varchar NOT NULL
);

CREATE TABLE "project_employee_types" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type_name" varchar UNIQUE
);

CREATE TABLE "project_employees" (
  "project_id" int NOT NULL,
  "employee_id" int NOT NULL
  -- "project_employee_type_id" int NOT NULL
);

CREATE TABLE "employees" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "prefix" varchar,
  "first_name" varchar,
  "last_name" varchar,
  "email" varchar UNIQUE,
  "major_id" int NOT NULL,
  "role_id" int NOT NULL
);

CREATE TABLE "comments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "project_id" int NOT NULL,
  "comment_text" text,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role_name" varchar UNIQUE
);

CREATE TABLE "resource_types" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "resource_type" varchar UNIQUE
);

CREATE TABLE "resources" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar,
  "resource_type_id" int NOT NULL,
  "url" varchar,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "asset_resources" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "resource_id" int,
  "description" varchar,
  "major_id" int NOT NULL
);

CREATE TABLE "project_resources" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "resource_id" int,
  "project_id" int NOT NULL
);

CREATE TABLE "project_resource_configs" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar,
  "resource_type_id" int NOT NULL,
  "major_id" int NOT NULL
);

CREATE TABLE "calendar" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "major_id" int NOT NULL,
  "event_date" date,
  "title" varchar,
  "description" text
);

ALTER TABLE "project_number_counters" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "students" ADD FOREIGN KEY ("major_id") REFERENCES "majors" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("major_id") REFERENCES "majors" ("id");

ALTER TABLE "projects" ADD FOREIGN KEY ("old_project_no") REFERENCES "projects" ("project_no");

ALTER TABLE "projects" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "projects" ADD FOREIGN KEY ("major_id") REFERENCES "majors" ("id");

ALTER TABLE "project_students" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");

ALTER TABLE "project_students" ADD FOREIGN KEY ("student_id") REFERENCES "students" ("id");

ALTER TABLE "project_employees" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");

ALTER TABLE "project_employees" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("id");

-- ALTER TABLE "project_employees" ADD FOREIGN KEY ("project_employee_type_id") REFERENCES "project_employee_types" ("id");

ALTER TABLE "employees" ADD FOREIGN KEY ("major_id") REFERENCES "majors" ("id");

ALTER TABLE "employees" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");

ALTER TABLE "comments" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");

ALTER TABLE "resources" ADD FOREIGN KEY ("resource_type_id") REFERENCES "resource_types" ("id");

ALTER TABLE "asset_resources" ADD FOREIGN KEY ("resource_id") REFERENCES "resources" ("id");

ALTER TABLE "asset_resources" ADD FOREIGN KEY ("major_id") REFERENCES "majors" ("id");

ALTER TABLE "project_resources" ADD FOREIGN KEY ("resource_id") REFERENCES "resources" ("id");

ALTER TABLE "project_resources" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");

ALTER TABLE "project_resource_configs" ADD FOREIGN KEY ("resource_type_id") REFERENCES "resource_types" ("id");

ALTER TABLE "project_resource_configs" ADD FOREIGN KEY ("major_id") REFERENCES "majors" ("id");

ALTER TABLE "calendar" ADD FOREIGN KEY ("major_id") REFERENCES "majors" ("id");
