services:
  project_service:
    # build: .
    image: kunmhing/projectservice:2.3
    container_name: project_service
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    # volumes:
    #   # - .:/app
    #   - project_service_data:/app
    working_dir: /app
    depends_on:
      - rabbitmq
      - postgres
      - minio
    networks:
      - project_box_net

  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_NAME}
    volumes:
      - project_box_data:/var/lib/postgresql/data
      - ./db/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/migrations/mock_data.sql:/docker-entrypoint-initdb.d/mock_data.sql
    networks:
      - project_box_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: unless-stopped
    ports:
      - "8888:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_ADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PG_ADMIN_PASSWORD}
    volumes:
      - project_box_pgadmin_data:/var/lib/pgadmin
    networks:
      - project_box_net

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"
      - "rabbitmq_log:/var/log/rabbitmq"
    networks:
      - project_box_net

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - "minio_data:/data"
    command: server --address ":9001" --console-address ":9000" /data
    networks:
      - project_box_net

volumes:
  project_box_data:
  project_box_pgadmin_data:
  minio_data:
  rabbitmq_data:
  rabbitmq_log:
  # project_service_data:

networks:
  project_box_net:
    external: false
