// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	db3 "github.com/project-box/db/minio"
	"github.com/project-box/db/postgres"
	db2 "github.com/project-box/db/rabbitmq"
	"github.com/project-box/handlers"
	"github.com/project-box/repositories"
	"github.com/project-box/services"
)

// Injectors from wire.go:

func InitializeApp() (*gin.Engine, func(), error) {
	gormDB := db.NewPostgresDatabase()
	channel := db2.NewRabbitMQConnection()
	client := db3.NewMinIOConnection()
	projectRepository := repositories.NewProjectRepository(gormDB, client)
	employeeRepository := repositories.NewEmployeeRepository(gormDB)
	majorRepository := repositories.NewMajorRepository(gormDB)
	sectionRepository := repositories.NewSectionRepository(gormDB)
	projectNumberCounterRepository := repositories.NewProjectNumberCounterRepository(gormDB)
	projectService := services.NewProjectService(channel, projectRepository, employeeRepository, majorRepository, sectionRepository, projectNumberCounterRepository)
	projectHandler := handlers.NewProjectHandler(projectService)
	engine, err := NewApp(gormDB, channel, projectHandler, client)
	if err != nil {
		return nil, nil, err
	}
	return engine, func() {
	}, nil
}

// wire.go:

var AppSet = wire.NewSet(
	NewApp, db.NewPostgresDatabase, db3.NewMinIOConnection, db2.NewRabbitMQConnection,
)

var HandlerSet = wire.NewSet(handlers.NewProjectHandler)

var ServiceSet = wire.NewSet(services.NewProjectService)

var RepositorySet = wire.NewSet(repositories.NewProjectRepository, repositories.NewProjectNumberCounterRepository, repositories.NewEmployeeRepository, repositories.NewMajorRepository, repositories.NewSectionRepository, repositories.NewResourceRepository)

var RedisSet = wire.NewSet()
