definitions:
  dtos.CalendarResponse:
    properties:
      description:
        type: string
      end_date:
        type: string
      id:
        type: integer
      major_name:
        type: string
      start_date:
        type: string
      title:
        type: string
    type: object
  dtos.CreateCalendarRequest:
    properties:
      description:
        type: string
      end_date:
        type: string
      major_id:
        type: integer
      start_date:
        type: string
      title:
        type: string
    type: object
  dtos.UpdateCalendarRequest:
    properties:
      description:
        type: string
      end_date:
        type: string
      id:
        type: integer
      major_id:
        type: integer
      start_date:
        type: string
      title:
        type: string
    type: object
  models.Course:
    properties:
      course_name:
        type: string
      course_no:
        type: string
      id:
        type: integer
      major:
        $ref: '#/definitions/models.Major'
      major_id:
        type: integer
    type: object
  models.Employee:
    properties:
      email:
        type: string
      first_name:
        type: string
      id:
        type: integer
      last_name:
        type: string
      major:
        $ref: '#/definitions/models.Major'
      major_id:
        type: integer
      prefix:
        type: string
      projects:
        items:
          $ref: '#/definitions/models.Project'
        type: array
    type: object
  models.Major:
    properties:
      id:
        type: integer
      major_name:
        type: string
    type: object
  models.PDF:
    properties:
      id:
        type: integer
      pages:
        items:
          $ref: '#/definitions/models.PDFPage'
        type: array
      resource_id:
        type: integer
    type: object
  models.PDFPage:
    properties:
      content:
        type: string
      id:
        type: integer
      page_number:
        type: integer
      pdf_id:
        description: Foreign key
        type: integer
    type: object
  models.Project:
    properties:
      abstract_text:
        type: string
      academic_year:
        type: integer
      course:
        $ref: '#/definitions/models.Course'
      course_id:
        type: integer
      created_at:
        type: string
      employees:
        items:
          $ref: '#/definitions/models.Employee'
        type: array
      id:
        type: integer
      is_approved:
        type: boolean
      major:
        $ref: '#/definitions/models.Major'
      major_id:
        type: integer
      members:
        items:
          $ref: '#/definitions/models.Student'
        type: array
      project_no:
        type: string
      project_resources:
        items:
          $ref: '#/definitions/models.ProjectResource'
        type: array
      section_id:
        type: string
      semester:
        type: integer
      title_en:
        type: string
      title_th:
        type: string
    type: object
  models.ProjectResource:
    properties:
      id:
        type: integer
      resource:
        $ref: '#/definitions/models.Resource'
    type: object
  models.Resource:
    properties:
      created_at:
        type: string
      id:
        type: integer
      path:
        type: string
      pdf:
        $ref: '#/definitions/models.PDF'
      resource_name:
        type: string
      resource_type:
        $ref: '#/definitions/models.ResourceType'
      resource_type_id:
        type: integer
      title:
        type: string
    type: object
  models.ResourceType:
    properties:
      id:
        type: integer
      mime_type:
        type: string
    type: object
  models.ResponseMessage:
    properties:
      message:
        type: string
    type: object
  models.Student:
    properties:
      email:
        description: Unique email address
        type: string
      first_name:
        description: First name of the student
        type: string
      id:
        description: Use `ID` as the primary key
        type: string
      last_name:
        description: Last name of the student
        type: string
      major:
        allOf:
        - $ref: '#/definitions/models.Major'
        description: Major related to student
      major_id:
        description: Major ID, not null
        type: integer
      prefix:
        description: Optional field for title (e.g., Mr., Ms., etc.)
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /calendar:
    post:
      consumes:
      - application/json
      description: Creates a new calendarof that major
      parameters:
      - description: Calendar Data
        in: body
        name: project
        required: true
        schema:
          $ref: '#/definitions/dtos.CreateCalendarRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Successfully created calendar
          schema:
            $ref: '#/definitions/dtos.CalendarResponse'
        "400":
          description: Invalid request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Create a new Calendar
      tags:
      - Calendar
    put:
      consumes:
      - application/json
      description: Updates an event by its ID with the provided data
      parameters:
      - description: Updated Event Data
        in: body
        name: event
        required: true
        schema:
          $ref: '#/definitions/dtos.UpdateCalendarRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully updated event
          schema:
            $ref: '#/definitions/dtos.CalendarResponse'
        "400":
          description: Invalid event ID or request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Update an existing event
      tags:
      - Calendar
  /calendar/GetByMajorID/{major_id}:
    get:
      description: Fetches all calendar events for a given major
      parameters:
      - description: Major ID
        in: path
        name: major_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved calendar events
          schema:
            items:
              $ref: '#/definitions/dtos.CalendarResponse'
            type: array
        "400":
          description: Invalid major ID
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Calendar events not found
          schema:
            additionalProperties: true
            type: object
      summary: Get calendar by major ID
      tags:
      - Calendar
  /projectResource/{id}:
    delete:
      description: Delete a resource and its file
      parameters:
      - description: Resource ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseMessage'
      summary: Delete a resource
      tags:
      - Resource
  /projects:
    post:
      consumes:
      - application/json
      description: Creates a new project with the provided data
      parameters:
      - description: Project Data
        in: body
        name: project
        required: true
        schema:
          $ref: '#/definitions/models.Project'
      produces:
      - application/json
      responses:
        "201":
          description: Successfully created project
          schema:
            $ref: '#/definitions/models.Project'
        "400":
          description: Invalid request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Create a new project
      tags:
      - Project
  /projects/{id}:
    delete:
      description: Deletes the specified project using its ID
      parameters:
      - description: Project ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Project deleted successfully
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid project ID
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Delete a project by ID
      tags:
      - Project
    get:
      description: Fetches a project by its unique ID
      parameters:
      - description: Project ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved project
          schema:
            $ref: '#/definitions/models.Project'
        "400":
          description: Invalid project ID
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Project not found
          schema:
            additionalProperties: true
            type: object
      summary: Get a project by ID
      tags:
      - Project
    put:
      consumes:
      - application/json
      description: Updates a project by its ID with the provided data
      parameters:
      - description: Project ID
        in: path
        name: id
        required: true
        type: integer
      - description: Updated Project Data
        in: body
        name: project
        required: true
        schema:
          $ref: '#/definitions/models.Project'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully updated project
          schema:
            $ref: '#/definitions/models.Project'
        "400":
          description: Invalid project ID or request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Update an existing project
      tags:
      - Project
  /projects/student/{student_id}:
    get:
      description: Fetches a project by its student ID
      parameters:
      - description: Student ID
        in: path
        name: student_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved project
          schema:
            items:
              $ref: '#/definitions/models.Project'
            type: array
        "400":
          description: Invalid student ID
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Project not found
          schema:
            additionalProperties: true
            type: object
      summary: Get a project by Student ID
      tags:
      - Project
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
